package model;
// Generated 14/04/2019 16:40:27 by Hibernate Tools 4.3.1



/**
 * Additionalitem generated by hbm2java
 */
public class Additionalitem  implements java.io.Serializable {


     private int code;
     private Additional additional;
     private Item item;

    public Additionalitem() {
    }

	
    public Additionalitem(int code) {
        this.code = code;
    }
    public Additionalitem(int code, Additional additional, Item item) {
       this.code = code;
       this.additional = additional;
       this.item = item;
    }
   
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }
    public Additional getAdditional() {
        return this.additional;
    }
    
    public void setAdditional(Additional additional) {
        this.additional = additional;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }




}


