package model;
// Generated 14/04/2019 16:40:27 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Additional generated by hbm2java
 */
public class Additional  implements java.io.Serializable {


     private int code;
     private Category category;
     private String description;
     private BigDecimal price;
     private String active;
     private Set requestadditionalitems = new HashSet(0);
     private Set additionalitems = new HashSet(0);

    public Additional() {
    }

	
    public Additional(int code) {
        this.code = code;
    }
    public Additional(int code, Category category, String description, BigDecimal price, String active, Set requestadditionalitems, Set additionalitems) {
       this.code = code;
       this.category = category;
       this.description = description;
       this.price = price;
       this.active = active;
       this.requestadditionalitems = requestadditionalitems;
       this.additionalitems = additionalitems;
    }
   
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }
    public Set getRequestadditionalitems() {
        return this.requestadditionalitems;
    }
    
    public void setRequestadditionalitems(Set requestadditionalitems) {
        this.requestadditionalitems = requestadditionalitems;
    }
    public Set getAdditionalitems() {
        return this.additionalitems;
    }
    
    public void setAdditionalitems(Set additionalitems) {
        this.additionalitems = additionalitems;
    }




}


