package model;
// Generated 14/04/2019 16:40:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private int code;
     private String description;
     private Set additionals = new HashSet(0);
     private Set items = new HashSet(0);
     private Set filterhistories = new HashSet(0);

    public Category() {
    }

	
    public Category(int code) {
        this.code = code;
    }
    public Category(int code, String description, Set additionals, Set items, Set filterhistories) {
       this.code = code;
       this.description = description;
       this.additionals = additionals;
       this.items = items;
       this.filterhistories = filterhistories;
    }
   
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getAdditionals() {
        return this.additionals;
    }
    
    public void setAdditionals(Set additionals) {
        this.additionals = additionals;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }
    public Set getFilterhistories() {
        return this.filterhistories;
    }
    
    public void setFilterhistories(Set filterhistories) {
        this.filterhistories = filterhistories;
    }




}


