package model;
// Generated 14/04/2019 16:40:27 by Hibernate Tools 4.3.1



/**
 * Comboitem generated by hbm2java
 */
public class Comboitem  implements java.io.Serializable {


     private int code;
     private Item itemByCodeItem;
     private Item itemByCodeComboitem;
     private Integer countitem;

    public Comboitem() {
    }

	
    public Comboitem(int code) {
        this.code = code;
    }
    public Comboitem(int code, Item itemByCodeItem, Item itemByCodeComboitem, Integer countitem) {
       this.code = code;
       this.itemByCodeItem = itemByCodeItem;
       this.itemByCodeComboitem = itemByCodeComboitem;
       this.countitem = countitem;
    }
   
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }
    public Item getItemByCodeItem() {
        return this.itemByCodeItem;
    }
    
    public void setItemByCodeItem(Item itemByCodeItem) {
        this.itemByCodeItem = itemByCodeItem;
    }
    public Item getItemByCodeComboitem() {
        return this.itemByCodeComboitem;
    }
    
    public void setItemByCodeComboitem(Item itemByCodeComboitem) {
        this.itemByCodeComboitem = itemByCodeComboitem;
    }
    public Integer getCountitem() {
        return this.countitem;
    }
    
    public void setCountitem(Integer countitem) {
        this.countitem = countitem;
    }




}


