package model;
// Generated 14/04/2019 16:40:27 by Hibernate Tools 4.3.1



/**
 * Enableinsert generated by hbm2java
 */
public class Enableinsert  implements java.io.Serializable {


     private int code;
     private String tablelist;
     private String guestcheck;

    public Enableinsert() {
    }

	
    public Enableinsert(int code) {
        this.code = code;
    }
    public Enableinsert(int code, String tablelist, String guestcheck) {
       this.code = code;
       this.tablelist = tablelist;
       this.guestcheck = guestcheck;
    }
   
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }
    public String getTablelist() {
        return this.tablelist;
    }
    
    public void setTablelist(String tablelist) {
        this.tablelist = tablelist;
    }
    public String getGuestcheck() {
        return this.guestcheck;
    }
    
    public void setGuestcheck(String guestcheck) {
        this.guestcheck = guestcheck;
    }




}


