package model;
// Generated 14/04/2019 16:40:27 by Hibernate Tools 4.3.1



/**
 * Filterhistory generated by hbm2java
 */
public class Filterhistory  implements java.io.Serializable {


     private int code;
     private Category category;

    public Filterhistory() {
    }

	
    public Filterhistory(int code) {
        this.code = code;
    }
    public Filterhistory(int code, Category category) {
       this.code = code;
       this.category = category;
    }
   
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }




}


