package model;
// Generated 14/04/2019 16:40:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Guestcheck generated by hbm2java
 */
public class Guestcheck  implements java.io.Serializable {


     private int code;
     private String barcode;
     private String active;
     private Set requests = new HashSet(0);

    public Guestcheck() {
    }

	
    public Guestcheck(int code) {
        this.code = code;
    }
    public Guestcheck(int code, String barcode, String active, Set requests) {
       this.code = code;
       this.barcode = barcode;
       this.active = active;
       this.requests = requests;
    }
   
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }
    public String getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }
    public Set getRequests() {
        return this.requests;
    }
    
    public void setRequests(Set requests) {
        this.requests = requests;
    }




}


