package model;
// Generated 14/04/2019 16:40:27 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Requestitem generated by hbm2java
 */
public class Requestitem  implements java.io.Serializable {


     private int code;
     private Item item;
     private Request request;
     private String status;
     private Integer countitem;
     private String note;
     private Character checkRequeststart;
     private Date datetimeins;
     private Date datetimeupd;
     private Set requestadditionalitems = new HashSet(0);

    public Requestitem() {
    }

	
    public Requestitem(int code) {
        this.code = code;
    }
    public Requestitem(int code, Item item, Request request, String status, Integer countitem, String note, Character checkRequeststart, Date datetimeins, Date datetimeupd, Set requestadditionalitems) {
       this.code = code;
       this.item = item;
       this.request = request;
       this.status = status;
       this.countitem = countitem;
       this.note = note;
       this.checkRequeststart = checkRequeststart;
       this.datetimeins = datetimeins;
       this.datetimeupd = datetimeupd;
       this.requestadditionalitems = requestadditionalitems;
    }
   
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Request getRequest() {
        return this.request;
    }
    
    public void setRequest(Request request) {
        this.request = request;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Integer getCountitem() {
        return this.countitem;
    }
    
    public void setCountitem(Integer countitem) {
        this.countitem = countitem;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Character getCheckRequeststart() {
        return this.checkRequeststart;
    }
    
    public void setCheckRequeststart(Character checkRequeststart) {
        this.checkRequeststart = checkRequeststart;
    }
    public Date getDatetimeins() {
        return this.datetimeins;
    }
    
    public void setDatetimeins(Date datetimeins) {
        this.datetimeins = datetimeins;
    }
    public Date getDatetimeupd() {
        return this.datetimeupd;
    }
    
    public void setDatetimeupd(Date datetimeupd) {
        this.datetimeupd = datetimeupd;
    }
    public Set getRequestadditionalitems() {
        return this.requestadditionalitems;
    }
    
    public void setRequestadditionalitems(Set requestadditionalitems) {
        this.requestadditionalitems = requestadditionalitems;
    }




}


