package model;
// Generated 14/04/2019 16:40:27 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Request generated by hbm2java
 */
public class Request  implements java.io.Serializable {


     private int code;
     private Guestcheck guestcheck;
     private Tablelist tablelist;
     private String status;
     private Date datetimeins;
     private Date datetimeend;
     private BigDecimal paymoney;
     private BigDecimal paycard;
     private String cardtype;
     private Set requestitems = new HashSet(0);

    public Request() {
    }

	
    public Request(int code) {
        this.code = code;
    }
    public Request(int code, Guestcheck guestcheck, Tablelist tablelist, String status, Date datetimeins, Date datetimeend, BigDecimal paymoney, BigDecimal paycard, String cardtype, Set requestitems) {
       this.code = code;
       this.guestcheck = guestcheck;
       this.tablelist = tablelist;
       this.status = status;
       this.datetimeins = datetimeins;
       this.datetimeend = datetimeend;
       this.paymoney = paymoney;
       this.paycard = paycard;
       this.cardtype = cardtype;
       this.requestitems = requestitems;
    }
   
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }
    public Guestcheck getGuestcheck() {
        return this.guestcheck;
    }
    
    public void setGuestcheck(Guestcheck guestcheck) {
        this.guestcheck = guestcheck;
    }
    public Tablelist getTablelist() {
        return this.tablelist;
    }
    
    public void setTablelist(Tablelist tablelist) {
        this.tablelist = tablelist;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getDatetimeins() {
        return this.datetimeins;
    }
    
    public void setDatetimeins(Date datetimeins) {
        this.datetimeins = datetimeins;
    }
    public Date getDatetimeend() {
        return this.datetimeend;
    }
    
    public void setDatetimeend(Date datetimeend) {
        this.datetimeend = datetimeend;
    }
    public BigDecimal getPaymoney() {
        return this.paymoney;
    }
    
    public void setPaymoney(BigDecimal paymoney) {
        this.paymoney = paymoney;
    }
    public BigDecimal getPaycard() {
        return this.paycard;
    }
    
    public void setPaycard(BigDecimal paycard) {
        this.paycard = paycard;
    }
    public String getCardtype() {
        return this.cardtype;
    }
    
    public void setCardtype(String cardtype) {
        this.cardtype = cardtype;
    }
    public Set getRequestitems() {
        return this.requestitems;
    }
    
    public void setRequestitems(Set requestitems) {
        this.requestitems = requestitems;
    }




}


