package model;
// Generated 14/04/2019 16:40:27 by Hibernate Tools 4.3.1



/**
 * Requestadditionalitem generated by hbm2java
 */
public class Requestadditionalitem  implements java.io.Serializable {


     private int code;
     private Additional additional;
     private Requestitem requestitem;

    public Requestadditionalitem() {
    }

	
    public Requestadditionalitem(int code) {
        this.code = code;
    }
    public Requestadditionalitem(int code, Additional additional, Requestitem requestitem) {
       this.code = code;
       this.additional = additional;
       this.requestitem = requestitem;
    }
   
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }
    public Additional getAdditional() {
        return this.additional;
    }
    
    public void setAdditional(Additional additional) {
        this.additional = additional;
    }
    public Requestitem getRequestitem() {
        return this.requestitem;
    }
    
    public void setRequestitem(Requestitem requestitem) {
        this.requestitem = requestitem;
    }




}


