package model;
// Generated 14/04/2019 16:40:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tablelist generated by hbm2java
 */
public class Tablelist  implements java.io.Serializable {


     private int code;
     private String description;
     private String active;
     private Set requests = new HashSet(0);

    public Tablelist() {
    }

	
    public Tablelist(int code) {
        this.code = code;
    }
    public Tablelist(int code, String description, String active, Set requests) {
       this.code = code;
       this.description = description;
       this.active = active;
       this.requests = requests;
    }
   
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }
    public Set getRequests() {
        return this.requests;
    }
    
    public void setRequests(Set requests) {
        this.requests = requests;
    }




}


