package model;
// Generated 18/04/2019 20:08:14 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Userlog generated by hbm2java
 */
@Entity
@Table(name="userlog"
    ,schema="sis_comanda"
)
public class Userlog  implements java.io.Serializable {


     private int code;
     private Userlogin userlogin;
     private Date datetimeins;
     private String logtype;

    public Userlog() {
    }

	
    public Userlog(Userlogin userlogin) {
        this.userlogin = userlogin;
    }
    public Userlog(Userlogin userlogin, Date datetimeins, String logtype) {
       this.userlogin = userlogin;
       this.datetimeins = datetimeins;
       this.logtype = logtype;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="userlogin"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="code", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Userlogin getUserlogin() {
        return this.userlogin;
    }
    
    public void setUserlogin(Userlogin userlogin) {
        this.userlogin = userlogin;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datetimeins", length=29)
    public Date getDatetimeins() {
        return this.datetimeins;
    }
    
    public void setDatetimeins(Date datetimeins) {
        this.datetimeins = datetimeins;
    }

    
    @Column(name="logtype", length=10)
    public String getLogtype() {
        return this.logtype;
    }
    
    public void setLogtype(String logtype) {
        this.logtype = logtype;
    }




}


