package model;
// Generated 24/04/2019 22:28:50 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Enableinsert generated by hbm2java
 */
@Entity
@Table(name="enableinsert"
    ,schema="sis_comanda"
)
public class Enableinsert  implements java.io.Serializable {


     private int code;
     private String tablelist;
     private String guestcheck;

    public Enableinsert() {
    }

	
    public Enableinsert(int code) {
        this.code = code;
    }
    public Enableinsert(int code, String tablelist, String guestcheck) {
       this.code = code;
       this.tablelist = tablelist;
       this.guestcheck = guestcheck;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

    
    @Column(name="tablelist", length=3)
    public String getTablelist() {
        return this.tablelist;
    }
    
    public void setTablelist(String tablelist) {
        this.tablelist = tablelist;
    }

    
    @Column(name="guestcheck", length=3)
    public String getGuestcheck() {
        return this.guestcheck;
    }
    
    public void setGuestcheck(String guestcheck) {
        this.guestcheck = guestcheck;
    }




}


