package model;
// Generated 24/04/2019 22:28:50 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Filterhistory generated by hbm2java
 */
@Entity
@Table(name="filterhistory"
    ,schema="sis_comanda"
)
public class Filterhistory  implements java.io.Serializable {


     private int code;
     private Category category;

    public Filterhistory() {
    }

	
    public Filterhistory(int code) {
        this.code = code;
    }
    public Filterhistory(int code, Category category) {
       this.code = code;
       this.category = category;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="code_category")
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }




}


