package model;
// Generated 24/04/2019 22:28:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Guestcheck generated by hbm2java
 */
@Entity
@Table(name="guestcheck"
    ,schema="sis_comanda"
    , uniqueConstraints = @UniqueConstraint(columnNames="barcode") 
)
public class Guestcheck  implements java.io.Serializable {


     private int code;
     private String barcode;
     private String active;
     private Set<Request> requests = new HashSet<Request>(0);

    public Guestcheck() {
    }

	
    public Guestcheck(int code) {
        this.code = code;
    }
    public Guestcheck(int code, String barcode, String active, Set<Request> requests) {
       this.code = code;
       this.barcode = barcode;
       this.active = active;
       this.requests = requests;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

    
    @Column(name="barcode", unique=true, length=10)
    public String getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    
    @Column(name="active", length=3)
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="guestcheck")
    public Set<Request> getRequests() {
        return this.requests;
    }
    
    public void setRequests(Set<Request> requests) {
        this.requests = requests;
    }




}


