package model;
// Generated 24/04/2019 22:28:50 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Userlogin generated by hbm2java
 */
@Entity
@Table(name="userlogin"
    ,schema="sis_comanda"
)
public class Userlogin  implements java.io.Serializable {


     private int code;
     private String name;
     private String login;
     private String password;
     private String active;
     private Userlog userlog;
     private Userpermission userpermission;

    public Userlogin() {
    }

	
    public Userlogin(int code) {
        this.code = code;
    }
    public Userlogin(int code, String name, String login, String password, String active, Userlog userlog, Userpermission userpermission) {
       this.code = code;
       this.name = name;
       this.login = login;
       this.password = password;
       this.active = active;
       this.userlog = userlog;
       this.userpermission = userpermission;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

    
    @Column(name="name", length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="login", length=20)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="password", length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="active", length=3)
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="userlogin")
    public Userlog getUserlog() {
        return this.userlog;
    }
    
    public void setUserlog(Userlog userlog) {
        this.userlog = userlog;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="userlogin")
    public Userpermission getUserpermission() {
        return this.userpermission;
    }
    
    public void setUserpermission(Userpermission userpermission) {
        this.userpermission = userpermission;
    }




}


